n1 = (input(str("Enter your first name: ")))
n2 = (input(str("Enter your last name: ")))
n3 = (input(str("Enter your age: ")))
n4 = (input(str("Enter your house name: ")))
n5 = (input(str("Welcome! Please enter the sport you are joining: ")))
print(" ")
print("Form submitted! Here are your details: ")
print("Name: "+ n1+" "+n2)
print("Age: "+n3)
print("House: "+n4)
print("Sport: "+n5)
